[package]
name = "generate-ssh-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.76"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
log = { version = "0.4.20", features = ["std", "serde"] }
